# -*- coding: utf-8 -*-
"""PaymentFraud.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nqJ_bhQpCy39kWetEAI0GM2DzCCoHESj
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.preprocessing import OneHotEncoder

df = pd.read_csv('/content/drive/MyDrive/payment_fraud.csv')
df.head()

#creating instance of one-hot-encoder
encoder = OneHotEncoder(handle_unknown='ignore')

#perform one-hot encoding on 'team' column
encoder_df = pd.DataFrame(encoder.fit_transform(df[['paymentMethod']]).toarray())

#merge one-hot encoded columns back with original DataFrame
final_df = df.join(encoder_df)

# drop original column
df = df.drop('paymentMethod', axis = 1)

#view final df
print(final_df)

# Split dataset up into train and test sets
X_train, X_test, y_train, y_test = train_test_split(
    df.drop('label', axis=1), df['label'],
    test_size=0.33, random_state=17)

clf = LogisticRegression().fit(X_train, y_train)

# Make predictions on test set
y_pred = clf.predict(X_test)
from sklearn.metrics import accuracy_score
print(accuracy_score(y_pred, y_test))

# Compare test set predictions with ground truth labels
print(confusion_matrix(y_test, y_pred))
